"""Rule capture — when a bug escapes to production, generate a Semgrep rule
template to catch it next time. This is the feedback loop that makes the
pipeline smarter over time.
"""
from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Optional
from datetime import datetime


class RuleCapture:
    def __init__(self, repo_root: Path):
        self.repo_root = repo_root
        self.rules_dir = repo_root / ".loomscan-rules"
        self.rules_dir.mkdir(parents=True, exist_ok=True)

    def capture_escaped_bug(self, layer_id: str, file_path: str,
                            line: int, code_snippet: str,
                            bug_description: str,
                            language: str = "python") -> Path:
        """Generate a Semgrep rule template for an escaped bug.

        The user edits the rule to make it precise, then commits it. The
        next time similar code is committed, L0 (Semgrep) will catch it.
        """
        rule_id = f"escaped-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        filename = self.rules_dir / f"{rule_id}.yml"

        if language == "python":
            pattern = self._python_pattern_from_snippet(code_snippet)
        elif language in ("javascript", "typescript"):
            pattern = self._js_pattern_from_snippet(code_snippet)
        else:
            pattern = code_snippet.strip()

        rule_yaml = textwrap.dedent(f"""
            # Auto-generated by `loomscan feedback capture` on {datetime.now().isoformat()}
            # Bug description: {bug_description}
            # Escaped from layer: {layer_id}
            # Original location: {file_path}:{line}
            #
            # TODO: Refine the pattern below to be more precise.
            # Test it with: semgrep --config {filename.name} <file>

            rules:
              - id: {rule_id}
                pattern: {pattern}
                message: |
                  Possible bug: {bug_description}
                  (Captured from an escaped bug on {datetime.now().date()})
                languages: [{language}]
                severity: WARNING
                metadata:
                  source: loomscan-feedback
                  escaped_from: {layer_id}
                  original_file: {file_path}
                  original_line: {line}
        """).strip() + "\n"

        filename.write_text(rule_yaml, encoding="utf-8")
        return filename

    def _python_pattern_from_snippet(self, snippet: str) -> str:
        """Best-effort pattern extraction. The user will refine."""
        line = snippet.strip().splitlines()[0] if snippet.strip() else "..."
        # semgrep metavariables: replace identifiers with $X
        import re
        pattern = re.sub(r"\b[a-z_][a-z0-9_]*\b", lambda m: "$" + m.group(0).upper()
                         if not m.group(0).startswith("$") else m.group(0), line)
        return pattern

    def _js_pattern_from_snippet(self, snippet: str) -> str:
        return self._python_pattern_from_snippet(snippet)

    def list_captured_rules(self) -> list:
        return sorted(self.rules_dir.glob("*.yml"))
