"""LLM-as-rule-compiler with mutation verification.

Instead of writing rules manually, we ask the LLM to PROPOSE rules based on
each function's code. Then we verify each rule with mutation testing — a rule
is only kept if it catches at least one mutant (i.e., it would have caught a
real bug of that shape).

Pattern:
  1. For each function, ask the LLM: "What bugs could exist here? For each,
     give me a Semgrep rule that would catch it."
  2. LLM proposes N rules
  3. For each rule, mutate the function (e.g., change == to !=, remove a check)
  4. Run the rule against the mutated code
  5. If the rule fires on the mutant → it's useful, keep it
  6. If the rule doesn't fire on any mutant → it's noise, discard it

This is the "LLM as a compiler" pattern applied to rule generation. The LLM
runs ONCE per function; the rules run forever. And mutation testing ensures
we only keep rules that actually catch bugs.

This closes the "5,000 rules" gap intelligently — we don't write 5,000 rules,
we generate exactly the rules your codebase needs, verified to be useful.
"""
from __future__ import annotations

import ast
import json
import hashlib
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple
import subprocess
import tempfile
import sys


@dataclass
class GeneratedRule:
    """A rule generated by the LLM and verified by mutation testing."""
    rule_id: str
    function: str
    file: str
    description: str
    semgrep_yaml: str
    mutation_verified: bool
    mutants_caught: int


def generate_rules_for_function(func_name: str, func_body: str,
                                 language: str,
                                 llm_client=None) -> List[dict]:
    """Ask the LLM to propose Semgrep rules for a function.

    Returns a list of {rule_id, description, yaml} dicts.
    """
    if llm_client is None or not llm_client.is_available():
        return []

    prompt = f"""Analyze this {language} function and propose Semgrep rules that would catch
realistic bugs in similar code. For each rule, describe the bug it catches.

Function:
```{language}
{func_body[:1500]}
```

Respond in JSON:
{{
  "rules": [
    {{
      "rule_id": "descriptive-name",
      "description": "what bug this catches",
      "yaml": "the full Semgrep rule YAML"
    }}
  ]
}}

Rules:
- Each rule must be valid Semgrep YAML
- Pattern must be specific enough to avoid false positives
- Limit to 3-5 high-value rules
- Focus on bugs that could realistically occur (not style issues)
- Each rule should catch a DIFFERENT class of bug
"""
    raw = llm_client.generate(prompt, system="You are a security engineer who writes precise Semgrep rules.",
                               temperature=0.2)
    if not raw:
        return []
    try:
        start = raw.find("{")
        end = raw.rfind("}")
        if start == -1 or end == -1:
            return []
        data = json.loads(raw[start:end+1])
        return data.get("rules", [])
    except json.JSONDecodeError:
        return []


def mutate_function(func_body: str, language: str) -> List[str]:
    """Generate mutants of a function for testing rules.

    We do simple AST-based mutations:
      - == → !=
      - != → ==
      - > → >=
      - < → <=
      - + → -
      - and → or
      - or → and
      - remove `not` prefix
      - change `return X` to `return None`
    """
    if language != "python":
        return []  # only Python for now

    try:
        tree = ast.parse(func_body)
    except SyntaxError:
        return []

    mutants: List[str] = []

    class Mutator(ast.NodeTransformer):
        def __init__(self, mutation_type: str):
            self.mutation_type = mutation_type
            self.mutated = False

        def visit_Eq(self, node):
            if self.mutation_type == "eq_to_ne" and not self.mutated:
                self.mutated = True
                return ast.NotEq()
            return node

        def visit_NotEq(self, node):
            if self.mutation_type == "ne_to_eq" and not self.mutated:
                self.mutated = True
                return ast.Eq()
            return node

        def visit_Gt(self, node):
            if self.mutation_type == "gt_to_gte" and not self.mutated:
                self.mutated = True
                return ast.GtE()
            return node

        def visit_Lt(self, node):
            if self.mutation_type == "lt_to_lte" and not self.mutated:
                self.mutated = True
                return ast.LtE()
            return node

        def visit_Add(self, node):
            if self.mutation_type == "add_to_sub" and not self.mutated:
                self.mutated = True
                return ast.Sub()
            return node

        def visit_And(self, node):
            if self.mutation_type == "and_to_or" and not self.mutated:
                self.mutated = True
                return ast.Or()
            return node

        def visit_Or(self, node):
            if self.mutation_type == "or_to_and" and not self.mutated:
                self.mutated = True
                return ast.And()
            return node

    mutation_types = ["eq_to_ne", "ne_to_eq", "gt_to_gte", "lt_to_lte",
                      "add_to_sub", "and_to_or", "or_to_and"]

    for mtype in mutation_types:
        mutator = Mutator(mtype)
        try:
            mutated_tree = mutator.visit(ast.parse(func_body))
            ast.fix_missing_locations(mutated_tree)
            mutant = ast.unparse(mutated_tree)
            if mutant != func_body:
                mutants.append(mutant)
        except Exception:
            continue

    return mutants


def verify_rule_against_mutants(rule_yaml: str, func_body: str,
                                  language: str) -> Tuple[bool, int]:
    """Verify a rule by running it against mutants of the function.

    Returns (is_useful, mutants_caught).
    A rule is "useful" if it catches at least one mutant.
    """
    if not shutil.which("semgrep"):
        return True, 0  # can't verify — assume useful

    mutants = mutate_function(func_body, language)
    if not mutants:
        return True, 0  # no mutants possible — assume useful

    # write rule to temp file
    with tempfile.NamedTemporaryFile(mode="w", suffix=".yml", delete=False,
                                      encoding="utf-8") as f:
        f.write(rule_yaml)
        rule_path = Path(f.name)

    caught = 0
    try:
        for mutant in mutants:
            with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False,
                                              encoding="utf-8") as f:
                f.write(mutant)
                mutant_path = Path(f.name)
            try:
                proc = subprocess.run(
                    ["semgrep", "--config", str(rule_path), "--json", str(mutant_path)],
                    capture_output=True, text=True, check=False, timeout=10,
                )
                data = json.loads(proc.stdout or "{}")
                if data.get("results"):
                    caught += 1
            except Exception:
                continue
            finally:
                mutant_path.unlink(missing_ok=True)
    finally:
        rule_path.unlink(missing_ok=True)

    return caught > 0, caught


import shutil


def compile_rules_for_file(file_path: Path, repo_root: Path = None,
                            llm_client=None) -> List[GeneratedRule]:
    """End-to-end: generate and verify rules for all functions in a file.

    The LLM proposes rules; mutation testing verifies them. Only verified
    rules are returned.
    """
    if not file_path.exists() or file_path.suffix != ".py":
        return []

    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source)
    except Exception:
        return []

    rel_path = str(file_path.relative_to(repo_root)) if repo_root else str(file_path)
    language = "python"

    results: List[GeneratedRule] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_"):
            continue

        func_body = ast.unparse(node)
        proposed_rules = generate_rules_for_function(node.name, func_body, language, llm_client)

        for rule_dict in proposed_rules:
            yaml = rule_dict.get("yaml", "")
            if not yaml:
                continue
            # verify
            is_useful, caught = verify_rule_against_mutants(yaml, func_body, language)
            if not is_useful:
                continue  # rule doesn't catch any mutant — discard

            rule_id = f"llm-{node.name}-{hashlib.md5(yaml.encode()).hexdigest()[:8]}"
            results.append(GeneratedRule(
                rule_id=rule_id,
                function=node.name,
                file=rel_path,
                description=rule_dict.get("description", ""),
                semgrep_yaml=yaml,
                mutation_verified=True,
                mutants_caught=caught,
            ))

    return results


def save_generated_rules(rules: List[GeneratedRule], dest_dir: Path) -> List[Path]:
    """Save generated rules to .loomscan-rules/llm-compiled/."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    saved: List[Path] = []
    for rule in rules:
        path = dest_dir / f"{rule.rule_id}.yml"
        path.write_text(rule.semgrep_yaml, encoding="utf-8")
        saved.append(path)
    return saved
