"""Static HTML report generation — for sharing and CI artifacts."""
from __future__ import annotations

from pathlib import Path
from datetime import datetime
from typing import List

from ..models import PipelineResult, Finding, Severity, Decision


_SEV_COLOR = {
    Severity.CRITICAL: "#dc2626",
    Severity.HIGH: "#ea580c",
    Severity.MEDIUM: "#ca8a04",
    Severity.LOW: "#2563eb",
    Severity.INFO: "#6b7280",
}

_DECISION_COLOR = {
    Decision.BLOCK: "#dc2626",
    Decision.WARN: "#ca8a04",
    Decision.PASS: "#16a34a",
    Decision.UNCERTAIN: "#9333ea",
}


def to_html(result: PipelineResult, repo_root: Path) -> str:
    """Generate a self-contained HTML report."""
    by_sev = {}
    for f in result.findings:
        by_sev[f.severity.value] = by_sev.get(f.severity.value, 0) + 1

    final_color = _DECISION_COLOR.get(result.final_decision, "#000")
    rows_html = ""
    for i, (f, d) in enumerate(zip(result.findings, result.decisions), 1):
        sev_color = _SEV_COLOR.get(f.severity, "#000")
        dec_color = _DECISION_COLOR.get(d.decision, "#000")
        rows_html += f"""
        <tr>
          <td>{i}</td>
          <td><span class="badge" style="background:{sev_color}">{f.severity.value.upper()}</span></td>
          <td>{f.layer.value}</td>
          <td><span class="badge" style="background:{dec_color}">{d.decision.value.upper()}</span></td>
          <td class="mono">{f.file}:{f.start_line}</td>
          <td>{_escape(f.message)}</td>
          <td>{f.confidence:.0%}</td>
          <td>{f.exploitability:.0%}</td>
          <td>{f.blast_radius.value}</td>
          <td>{_escape(d.reasoning[:120])}</td>
        </tr>"""

    layers_html = ""
    for layer, t in sorted(result.layer_timings.items()):
        layers_html += f"<tr><td>{layer}</td><td>{t:.2f}s</td></tr>"

    sev_summary_html = " ".join(
        f'<span class="badge" style="background:{_SEV_COLOR.get(Severity(s), "#000")}">{s}: {c}</span>'
        for s, c in by_sev.items()
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>LoomScan Report — {datetime.now().isoformat(timespec='seconds')}</title>
  <style>
    body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 2em; background: #fafafa; color: #111; }}
    h1, h2, h3 {{ color: #111; }}
    .header {{ display: flex; justify-content: space-between; align-items: center; padding: 1em 1.5em; border-radius: 8px; color: white; }}
    .summary {{ display: flex; gap: 1em; margin: 1em 0; flex-wrap: wrap; }}
    .card {{ background: white; padding: 1em 1.5em; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); min-width: 150px; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; color: white; font-size: 0.85em; font-weight: 600; }}
    table {{ width: 100%; border-collapse: collapse; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; }}
    th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; font-size: 0.9em; }}
    th {{ background: #f3f4f6; font-weight: 600; }}
    .mono {{ font-family: "SF Mono", Monaco, monospace; font-size: 0.85em; color: #4b5563; }}
    .small {{ font-size: 0.85em; color: #6b7280; }}
  </style>
</head>
<body>
  <div class="header" style="background: {final_color};">
    <h1>LoomScan Report</h1>
    <div style="text-align: right;">
      <div style="font-size: 1.4em; font-weight: 700;">{result.final_decision.value.upper()}</div>
      <div class="small">{datetime.now().isoformat(timespec='seconds')}</div>
    </div>
  </div>

  <div class="summary">
    <div class="card"><div class="small">Findings</div><div style="font-size: 2em; font-weight: 700;">{len(result.findings)}</div></div>
    <div class="card"><div class="small">Diff hunks</div><div style="font-size: 2em; font-weight: 700;">{len(result.diff_hunks)}</div></div>
    <div class="card"><div class="small">LLM invoked</div><div style="font-size: 2em; font-weight: 700;">{"yes" if result.llm_invoked else "no"}</div></div>
    <div class="card"><div class="small">By severity</div><div>{sev_summary_html or "none"}</div></div>
  </div>

  <h2>Layer Timings</h2>
  <table><thead><tr><th>Layer</th><th>Time</th></tr></thead><tbody>{layers_html or '<tr><td colspan="2">No layers ran</td></tr>'}</tbody></table>

  <h2>Findings</h2>
  {"<table><thead><tr><th>#</th><th>Sev</th><th>Layer</th><th>Decision</th><th>File:Line</th><th>Message</th><th>Conf</th><th>Exploit</th><th>Blast</th><th>FIS Reasoning</th></tr></thead><tbody>" + rows_html + "</tbody></table>" if result.findings else "<p>No findings.</p>"}

  <p class="small">Generated by LoomScan v0.1.0 — deterministic-first, type-2 fuzzy aggregated.</p>
</body>
</html>"""


def _escape(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def save_html(result: PipelineResult, repo_root: Path, out_path: Path) -> None:
    out_path.write_text(to_html(result, repo_root), encoding="utf-8")
