"""One-shot LLM-based property test generation (Meta ACH-inspired pattern).

Generates Hypothesis property tests for each function, ONCE, and writes them
to tests/property/test_<module>_property.py. The tests are committed and run
deterministically on every subsequent commit.
"""
from __future__ import annotations

import ast
import textwrap
from pathlib import Path
from typing import List, Optional

from ..llm.client import LLMClient
from ..llm.prm import PRMScorer


class PropertyTestGenerator:
    def __init__(self, repo_root: Path, llm: Optional[LLMClient] = None):
        self.repo_root = repo_root
        self.llm = llm
        self.prm = PRMScorer()

    def generate_for_file(self, file_path: Path) -> Optional[Path]:
        if not file_path.exists():
            return None
        try:
            source = file_path.read_text(encoding="utf-8")
            tree = ast.parse(source)
        except Exception:
            return None

        # collect public functions
        functions = []
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if not node.name.startswith("_"):
                    functions.append(node)
        if not functions:
            return None

        rel_path = str(file_path.relative_to(self.repo_root))
        module_path = rel_path.replace("/", ".").replace(".py", "").lstrip(".")
        stem = file_path.stem
        out_dir = self.repo_root / "tests" / "property"
        out_path = out_dir / f"test_{stem}_property.py"
        if out_path.exists():
            return out_path

        # try LLM
        if self.llm and self.llm.is_available():
            test_code = self._llm_generate(functions, source, module_path)
            if test_code:
                out_dir.mkdir(parents=True, exist_ok=True)
                out_path.write_text(test_code, encoding="utf-8")
                return out_path

        # fallback: template
        return self._template_generate(functions, module_path, out_dir, out_path)

    def _llm_generate(self, functions: List[ast.FunctionDef],
                      source: str, module_path: str) -> Optional[str]:
        func_summary = "\n\n".join(
            f"def {n.name}({', '.join(a.arg for a in n.args.args)}): ..." for n in functions[:5]
        )
        prompt = f"""Generate Hypothesis property tests for these functions:

```python
{func_summary}
```

Module: `{module_path}`

Generate tests that:
1. Express invariants that should ALWAYS hold (e.g., round-trip, monotonicity, idempotence)
2. Use @given with appropriate Hypothesis strategies (st.integers, st.text, st.lists, etc.)
3. Don't test specific examples — test PROPERTIES
4. Are 5-15 lines each, including the @given decorator
5. Have clear docstrings explaining the property

Output ONLY Python code, no markdown fences.
"""
        raw = self.llm.generate(prompt, system="You are a Python testing expert specializing in property-based testing.",
                                temperature=0.2)
        if not raw:
            return None
        lines = raw.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        return "\n".join(lines)

    def _template_generate(self, functions: List[ast.FunctionDef],
                           module_path: str, out_dir: Path,
                           out_path: Path) -> Path:
        """Generate basic property tests based on function signatures."""
        test_funcs = []
        for func in functions[:3]:  # cap at 3
            args = [a.arg for a in func.args.args if a.arg != "self"]
            if not args:
                continue
            arg = args[0]
            test_funcs.append(textwrap.dedent(f'''
                @given(st.integers(min_value=-1000, max_value=1000))
                def test_{func.name}_does_not_crash({arg}):
                    """Property: {func.name} should not raise unexpected exceptions for any int input."""
                    try:
                        {func.name}({arg})
                    except (ValueError, TypeError):
                        pass  # acceptable
            ''').strip())

        if not test_funcs:
            return None

        code = textwrap.dedent(f'''
            """Auto-generated property tests for {module_path}.
            Generated by `loomscan bootstrap properties` (template fallback).
            Edit to add real property tests.
            """
            from hypothesis import given, strategies as st
            from {module_path} import *

        ''').strip() + "\n\n" + "\n\n".join(test_funcs) + "\n"

        out_dir.mkdir(parents=True, exist_ok=True)
        out_path.write_text(code, encoding="utf-8")
        return out_path
